### PR TITLE
Add optional data support for custom models

### LINKED ISSUE #4: Support optional data for custom models
Hi! In some cases optional `var`s for custom models are needed in addition to plain swift types.

For example:

``` swift
struct Profile {
    var identifier = 0
    var stats: Stats? = nil
}

extension Profile: ArrowParsable {
    init(json: JSON) {
        identifier <-- json["id"]
        stats <== json["stats"] // error
    }
}
```

The current implementation gives the following error for the above code: `Cannot convert value of type 'Stats?' to expected argument type 'inout _'`.

### PR DESCRIPTION
**Pull request by maxkonovalov**
Resolves #4

### CODE REVIEW

**Comment by s4cha** [comment]
This is great thank you so much :+1:

**Comment by maxkonovalov** [comment]
@s4cha - you're welcome 😀
I use `Arrow` via Carthage - will these changes propagate there? Or do you need to update it manually?

**Comment by s4cha** [comment]
You can try but I think we'll need to bump the tag number manually :)

**Comment by maxkonovalov** [comment]
Yup I did, it's not there yet ((

**Comment by s4cha** [comment]
Should work now (version 0.6) :)

**Comment by maxkonovalov** [comment]
Still not there... Maybe you should push the version to something like 0.6.1? There are two 0.6 releases, I think Carthage still checks out the older one.

**Comment by maxkonovalov** [comment]
I submitted another [PR](#6) - if you accept it, please bump up the version number, so that those changes are available via Carthage ;)

**Pull request merged**
