### PR TITLE
Add support for strings parsing

### PR DESCRIPTION
**Pull request by maxkonovalov**
Hey, don't know if this PR is appropriate for the original idea of the lib, but for me it is required to be able to parse numbers represented as strings in JSON to plain numeric types.

Consider the following JSON:

``` json
{ "id": "42" }
```

The current implementation fails to parse this case:

``` swift
int <-- json["id"] // does nothing
```

I added support for parsing basic numeric types (`Int`, `UInt`, `Bool`, `Double`, `Float`, `CGFloat` and corresponding optionals) from string, so the above no longer fails:

``` swift
int <-- json["id"] // = 42
double <-- json["id"] // = 42.0
```

Also added the ability to parse `NSDate` from timestamp (number or string):

``` swift
let json = ["timestamp": 392308720]
date <-- json["timestamp"]
```

Please feel free to modify this as you see fit :)

### CODE REVIEW

**Comment by s4cha** [comment]
Hey @maxkonovalov this is fantastic!

The way we would have to do it before was using Arrow to fill a temporary string value that we would have to manually parse afterwards. This automatises this use case and this is awesome. Nice one for the dates as well as it make Arrow more capable in terms of date formats.

Thanks a ton for this great work,

PS: I found a way to refactor the type operators you added to keep Arrow < 100 lines, you'll tell me what you think ;)

**Comment by s4cha** [comment]
@maxkonovalov what do you think of https://github.com/s4cha/Arrow/commit/50aba6c91da2d14fed6ec53b0f0209b8331fd476 ?
It brings us back to 100 lines of code 🎉

**Comment by maxkonovalov** [comment]
@s4cha wow, that's really cool))) what do you think of adding other integer types then, like `Int8`, `Int16`, etc.? I didn't add those to keep as little code as possible))
Btw, don't forget to change `<200lines` back to something like `~100lines` in README 😄

Also would be nice to add **arrays** support somehow - can you think of some options for that? I'd help if you like ;)

**Comment by s4cha** [comment]
@maxkonovalov yeah we can add other types for sure, I'm not sure the JSONSerialization would have all those types though, so we need to make sure we only add Types that actually exist in the realm of JSON :)
BTW Are you reading my mind? I just pushed :https://github.com/s4cha/Arrow/commit/0554dd43fe8b03ce888678448070a115339de9af and then saw your comment !

**Comment by maxkonovalov** [comment]
@s4cha nice work! parsing arrays of custom objects is a welcome feature really))
As for JSON types, it supports NSString, NSNumber, NSArray, NSDictionary, or NSNull, so I think all NSNumber types (including Int/UInt 8, 16, 32, 64) are worth adding just for the sake of completeness. Those are really rare use cases though :))

**Pull request merged**
