### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by maximkhatskevich**
- Minor bug fix ('collection' property wasn't available because it wasn't marked as 'public').
- Extended functionality (see 'ArrowInitializable' protocol and '<--/' infix operator).
- Improved code formatting to make it easy to read.
- Few minor code cleanups.

### CODE REVIEW

**Comment by s4cha** [comment]
Hi @maximkhatskevich,

First of all I would like to thank you for the time you took to put up this quite massive PR, and let you know that I am sorry for taking so long to reply.

This is full of nice improvements indeed :)

Unfortunately the code formatting has changed all over the place which is why it cannot be merged "as is".

From now on, we are going to rely on https://github.com/realm/SwiftLint formatting so that everyone stands on the same ground.

Apart from that, I really like the api improvements you suggest.

@maxkonovalov do you have any thoughts on that ?

Cheers,

**Comment by maxkonovalov** [comment]
Hey guys,
I agree that this PR is a good addition to the lib, but I believe that it needs some tweaks before merging:
- I prefer the original code formatting, the proposed one has too much linebreaks that don't make it easier to read but do the contrary and almost double the lines count. Besides, it doesn't look Swift-style but rather C++ or something like this. So I would suggest discarding the styling additions completely.
- The same concerns the `//===` and `// === MARK:` comments - they do not add any help and should be replaced with corresponding `// MARK: XXX`, `// MARK: - XXX` or `// MARK: - XXX -` variants, which are handled correctly by Xcode's jump bar.

On the `ArrowInitializable` protocol I think it's a good addition, but what do you guys think of changing the `<--/` operator to `<==` or something similar? (the latter was used in early Arrow versions).

**Comment by mxkh72** [comment]
Okay, guys. I'll fix formatting, thanks for the feedback!

**Comment by s4cha** [comment]
Hi @maximkhatskevich,

Your initial idea about the ArrowInitializable protocol has been implemented separately in https://github.com/freshOS/Arrow/pull/28

Thanks again for your work,

Closing this for now

**Comment by mxkh72** [comment]
Great, thanks!

**Pull request closed without merging**
